name: build

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: init
        run: |

          PARAMETERS="Sub='$SUB_TEST' Test='$TEST' Secret='$SECRET'"
          echo $PARAMETERS
        env:
          SUB_TEST: ${{ vars.SUB_TEST }}
          TEST: ${{ vars.TEST }}
          SECRET: ${{ secrets.SECRET }}
