name: CI in container

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
      
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: init
        run: |
          PARAMETERS="Sub='$SUB_TEST' Test='$TEST' Secret='$SECRET'"
          echo $PARAMETERS
        env:
          SUB_TEST: ${{ vars.SUB_TEST }}
          TEST: ${{ vars.TEST }}
          SECRET: ${{ secrets.SECRET }}
          
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

        
