name: CI in container

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
      
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Test If Condition
        shell: bash
        run: |
          #!/bin/bash -e
          
          if [ "$UNSET" == "default" ]; then
            echo "step ran : $UNSET"
          fi
          exit 0
        env:
          UNSET: ${{ vars.UNSET || 'Default' }}

      - name: check folder
        run: |
          echo "unset value : $UNSET"
          echo " Github workspace :  ${{ github.workspace }}"
          echo "current dir : $PWD"
          ls
        env:
          SUB_TEST: ${{ vars.SUB_TEST }}
          TEST: ${{ vars.TEST }}
          UNSET: ${{ vars.UNSET || 'Default' }}
          SECRET: ${{ secrets.SECRET }}

      - name: test node
        run: |
          node --version
          echo $SHELL
          
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

        
